[package]
name = "audiotool"
version.workspace = true
license.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
rx.workspace = true
rx.features = [
]

hound = "3.5.1"
libflac-sys = "0.3.0"
